[project]
name = "lifelog"
version = "0.1.0"
description = "This is the capstone project 'LifeLog'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg>=3.3.3",
    "psycopg-binary>=3.3.3",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "drf-spectacular>=0.29.0",
]
