# Generated by Django 6.0.2 on 2026-03-13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScanJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('receiving', 'Receiving'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('stored_file_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
