name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest
    environment: CapstoneCICDEnvironment

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Capstone_Backend
            git pull origin main
            make dev-down
            make dev-build
            sudo systemctl restart nginx
            make dev-up-d
            make dev-migrate