# Generated by Django 6.0.2 on 2026-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.TextField(unique=True)),
                ("platform", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
